### PR TITLE
Changes BlankNode to be an enum between anonymous and named blank nodes

### PR DESCRIPTION
**Pull request by Tpt**
Allows downstream libraries to make a difference between the two kinds of blank nodes.

### CODE REVIEW

**Comment by Tpt** [comment]
@pchampin What do you think about it?

**Comment by pchampin** [comment]
Is there a need for downstream libraries to make this difference? The distinction is not part of the RDF model (abstract syntax)...
I understand this could be useful for a better round-trip between parsers and serializers, but I'm affraid that would make the handling of bnodes generally more complicated.

That being said, in a *parser* API, this distinction makes sense -- and you leave the choice to downstream library developers to keep it or not.

To be honest, that will make it harder for me to implement Sophia traits on top of Rio types (`sophia` expect terms to expose a `&str`), but that should probably not be a show-stopper.

**Comment by Tpt** [comment]
> Is there a need for downstream libraries to make this difference? 

I was thinking about providing in Oxigraph a parser API that would keep the blank node ids provided by the serialization but use the 128bits random ids of Oxigraph for the other ones. But, I'm not sure it's really useful. I'm going to think more about it and revisit this PR if needed.

**Comment by pchampin** [comment]
Keeping the original bnode labels from the source file, and being able to distinguish "named" bnodes from "anonymous" bnodes, are orthogonal, in my view.

Granted, they are not *absolutely* orthogonal: if you are generated a "fake" label for "anonymous" bnodes, you have to ensure that it won't collide with a label from the file that you have not met yet. But there are reasonable heuristics to guarantee that (UUID or hashes comes to mind).

**Pull request closed without merging**
