### PR TITLE
Fix issue #46

### PR DESCRIPTION
**Pull request by pchampin**

### CODE REVIEW

**Comment by Tpt** [comment]
Cargo fmt seems unhappy with the change. If you want I can fix it myself and merge.

**Comment by pchampin** [comment]
Now fixed. Also, I fixed a remaining bug: clashes were still possible with the "disambiguating" labels that my code was generating.

**Comment by Tpt** [comment]
Thank you!

**Comment by Tpt** [comment]
Do you want me to publish a new release with this fix?

**Comment by pchampin** [comment]
No urgency on my side.

**Pull request merged**
