### PR TITLE
Feature/abbrev xml

### PR DESCRIPTION
**Pull request by phillord**
Not ready for merging

This is just my initial ideas about an API. I *think* this is enough to implement an abbreviated RDF formatted, although I am not sure yet. The `format` method might need tweaking to allow hints about what to do with a triple.

Addresses #39

### CODE REVIEW

**Comment by Tpt** [comment]
Thank you for this WIP!

A maybe bad idea to avoid the need for `AsRefNamedNode`: What about keeping in `AbbrevRdfXmlFormatter` (and `RdfXmlFormatter`) a `String` buffer and write into it the current IRI/bnode? It would add an extra copy but no allocation and would avoid the need for an extra trait. It would also avoid the allocation in case the serializer user give for input a `AsRefNamedNode<&str>`. I am not sure how much the extra copy will decrease performances but hopefully not much, `memcpy` is quite fast.

About `AbbrevRdfXmlFormatter`, what about `PrettyRdfXmlFormatter` instead? I guess we will want to provide more features than just abbreviations in it.

Instead of having `AbbrevRdfXmlFormatterConfig` we might also want to use the [builder pattern](https://doc.rust-lang.org/1.0.0/style/ownership/builders.html) that might be useful in our current case and is quite common in Rust. But it's cosmetic so fill free to stay with `AbbrevRdfXmlFormatterConfig` if you want.

Thank you again!

**Comment by phillord** [comment]
> A maybe bad idea to avoid the need for AsRefNamedNode: What about
 > just requiring that the input triples lifetime is longer than the
 > formatter lifetime? This way we would not need any new allocation
 > while avoiding the need for new traits.

That would require all the triples be held in memory (in front of the
parser) I think until the parse was complete? In my case, I would be
translating from another data structure, so I'd end up with everything
twice. In my case, the underlying data structure that I am using
stores everything as `Rc<String>` (which will become `Rc<str>` when I
get around to it), so `AsRef<str>` avoids the need for allocation that
way. Of course `'str` is also `AsRef<str>`, so one way to avoid the
new traits would be to use the `AsRef` versions for the whole library!

It also seems quite a way from the existing RdfXmlSerializer which
streams more or less entirely.


 > And for RdfXmlSerializer we would just use a single String buffer
 > to copy in it the current IRI/bnode subject. It would add an extra
 > copy but no allocation and would avoid the need for an extra trait
 > there too. It would also avoid the allocation in case the
 > serializer user give for input a AsRefNamedNode<&str>. I am not
 > sure how much the extra copy will decrease performances but
 > hopefully not much, memcpy is quite fast.

The BNode ellision code has to hold a lot more in memory (in worst
case the entire graph!), so I don't think that will work. Also, there
are some difficult questions to answer about the elision. AFAICT, it
can only be done accurately by pre-processing all the triples. At the
moment, it assumes that all the triples with a given BNode ID as
subject are before or immediately after the triple with that BNode as
an object. If that isn't true (and for some graphs it can never be!)
it's going to write the wrong thing.

As a micro optimization, I was going to wind the "split_iri" function
into `AsRefNamedNode` and memoize the results. I'm splitting the same
IRI several times at the moment.


 > About AbbrevRdfXmlFormatter, what about PrettyRdfXmlFormatter
 > instead? I guess we will want to provide more features than just
 > abbreviations in it.

 > Instead of having AbbrevRdfXmlFormatterConfig we might also want to
 > use the builder pattern that might be useful in our current case
 > and is quite common in Rust. But it's cosmetic so fill free to stay
 > with AbbrevRdfXmlFormatterConfig if you want.

I'm easy with either or both of these, and it's your API, so I am
happy to go with your thoughts. The config is mostly ignored at the
moment, anyway, it's just there for show! It would need some careful
testing to make sure that the various features work together.

 > Thank you again!

No worries. I need this code anyway and rio gives me something to
build on.

 > Edit: rewritten my "bad idea": the first version was bad indeed.

You should have seen the first version of my code!

**Comment by Tpt** [comment]
>>A maybe bad idea to avoid the need for AsRefNamedNode: What about  just requiring that the input triples lifetime is longer than the formatter lifetime? This way we would not need any new allocation while avoiding the need for new traits.

>That would require all the triples be held in memory (in front of the parser) I think until the parse was complete?

If we take for input a stream of `Triple<'a>` where `'a` has a longer lifetime than the writing, it would only require the term values (i.e. IRIs, blank node ids and literals values, language tag and datatypes) to be held in memory during the write. The `Triple`, `NamedNode`... structs themselves would still be given by value. This should be compatible with storing every values using `Rc<str>` in your code.

> It also seems quite a way from the existing RdfXmlSerializer which streams more or less entirely.

Yes, but anyway if we want to properly support blank node id elision we have to move away from streaming at least partially.

>> And for RdfXmlSerializer we would just use a single String buffer to copy in it the current IRI/bnode subject. It would add an extra copy but no allocation and would avoid the need for an extra trait there too. It would also avoid the allocation in case the serializer user give for input a AsRefNamedNode<&str>. I am not sure how much the extra copy will decrease performances but hopefully not much, memcpy is quite fast.

> The BNode ellision code has to hold a lot more in memory (in worst case the entire graph!), so I don't think that will work.

I believe there is a misunderstanding here. I was talking about the current `RdfXmlSerializer` that does everything in streaming and does not plan to support blank node elision. Sorry for my unclear wording. Indeed it would not work with blank node elision.

**Comment by phillord** [comment]
> If we take for input a stream of Triple<'a> where 'a has a longer lifetime than the writing, it would only require the term values (i.e. IRIs, blank node ids and literals values, language tag and datatypes) to be held in memory during the write. The Triple, NamedNode... structs themselves would still be given by value. This should be compatible with storing every values using Rc<str> in your code.

Hmmm. I'd have to see that. Rust isn't going to be able to work out the lifetime of the `Rc<str>`, since they are owned by a data structure form which they could be easily removed during the course of the write.


 > Yes, but anyway if we want to properly support blank node id
 > elision we have to move away from streaming at least partially.

That's true. I'm not sure how far yet. I've been trying to find a streaming parser for RDF XML abbrev, which I can copy the algorithm from. I worry that what I have at the moment will remain fragile.

**Comment by phillord** [comment]
So, my third attempt to get it right.

As well as being painful to achieve, I realised that the `pretty_formatter` code I was writing was spending a lot of time pushing Triples into a more complex data structure. This doesn't make sense for my use case because I already know a lot of the data structure I need before I make triples. For example, I know all the collection type elements; it makes no sense to pull them apart into triples only to have the formatter put them back together. Likewise, all the triples with a shared bnode subject will be produced together. I guess this is a common or main use case.

So, now we have a `chunked_formatter`. This allows you to specify collections, and group together bnodes. There is also code to do this for you, although this code currently has catastrophic performance (being quadratic with the number of triples in worse case, and in practice not much better), but that can be made linear and a bit with a few hash look ups. 

It's still not totally complete yet. There's one recursion bug that I have found. And the configuration and other parts needs cleaning.

So, key questions.

1) What do you think of the data model (`ExpandedTriple`, `MultiTriple`, `TripleSeq` and `RdfChunk`)? I think it should also work well for pretty versions of other formats, but I don't know them well.

2) My `AsRefTriple<A:AsRef<A>>` data structure generalizes your `Triple<'str>` and avoids a lot of complexity with life times. My code also involves a significant degree of cloning, and we cannot achieve this efficiently with `'str`. So, what to do? It would be possible to use the `AsRefTriple` as the main data model as it is a generalization. But equally that would probably be a significant amount of work.

**Comment by phillord** [comment]
I have started to use this for real now. The performance on a real world example is reasonable for me, even when not using streaming. I was hoping to mostly use the chunked interface for my use case, but it's actually quite difficult and given that it appears to be relatively quick just to generate all the triples then sort them after I may go for this.

So, I need to know how you would want to incorporate this into rio. As it stands, my code except in a few small ways, independent from Rio, although it mimics the API.

**Comment by Tpt** [comment]
Thank you so much for moving forward with it! It's great to hear that it is now working.

Indeed, this feature is not completely inside of the Rio main goal, that is to provide parsers. Because your PR code and API is mostly independent from `rio_xml` it might make sense to move it into its own crate that you would control. This way it will be possible to use it without pulling Rio parsers and use Rio RDF/XML parser without pulling the formatter code. It will also allow you to release your code without having to synchronize with the other Rio parts.

What do you think about it?

**Comment by phillord** [comment]
Well, on the pro's, yes, it would keep rio nice and simple and aimed at one thing.

On the negative side, while my data model is separate from Rio's, it's basically identical but with `'str` replaced with `AsRef<str>`. It seems a shame to have two data models for RDF where one would surely do. Or three, cause there is sophia also. The only obvious way that I can see to bring these together, though, is for you to switch Rio to the generic `AsRef<str>` with all that this entails. I do not think I can write a pretty formatter without liberal cloning, and `'str` does not allow that sanely. As far as I can tell, all the short hand syntaxes for RDF do similar tricks to the XML version, so I think it's also a question for you, whether you want to support any of those, because I suspect you will end up with a similar API. Indeed, to a certain extent you already have with `OwnedNamedNode` and the rest which can also be replaced by my `AsRefNamedNode<str>`.

From my perspective, I am mostly interested in RDF at the moment as a syntax for serializing OWL, and not it it's own right, so I'd rather it were integrated into something else, but as I say, it would require changes for Rio which feels like the tail wagging the dog. But if you did want to go that route, then I'd be happy to see this inside rio, whether directly as part of `rio_xml`, or as `rio_xml_chunked`.

**Comment by Tpt** [comment]
@phillord Thank you for your reply!

Indeed, we now have quite a lot of different models for RDF terms (Rio, Sophia, Oxigraph, your code...) and it would be nice to reduce the need for them.

>  do not think I can write a pretty formatter without liberal cloning, and 'str does not allow that sanely.

I am not sure to properly understand the problem here. If you generate all triples before doing the serialization, then the lifetime of the `'str` used in the triples is bigger than the one of the RDF serializers and it is possible to use them in the serializers data structures that will be dropped before the triples. And because `'str` implements `Copy` the triples and term are easy and cheap to clone. I have just written [a WIP very very basic and not optimized Turtle formatter that groups triples](https://github.com/oxigraph/rio/blob/cc66c4c159039a9b57ee8a679f5c77664499a899/turtle/src/formatters.rs#L377). I have added a `Rc` to the doc example. If you don't want to build all the `rio_api::Triple` in a `Vec`, it is possible to build them "on the fly" instead of the `triples.iter().cloned()` from your internal data structure.

**Comment by phillord** [comment]
Hmm. I don't generate all the triples before hand though. I generate the `Triple`, call `format` then drop the `Triple` while performing a recursive descent through my data model. As soon as I've rendered a part of the data model  (an OWL axiom, or expression in my case), I drop out of the scope where I have generated the `Triple`. That works fine for the normal formatter, because the `Triple` has been rendered and we are all done. It can safely be dropped. But, with the pretty formatter, I need to keep the `Triple` around for an arbitrary length of time, until it is formatted.

I guess I can keep all of the `Triple`s around outside of the formatter. But then that precludes the formatter using it's knowledge to understand what the `Triple`'s can go out of scope. For the simple formatter that will be immediately after `format` is called. For the pretty formatter it's not. And I need to store the `Triples` in a new data structure, when the `Formatter` object can just do the job for me.

The use of `AsRef<str>` means that the, if all the `Triple` objects are kept around anyway, you can use `'str' or you can use `Rc<str>` if not.

**Comment by Tpt** [comment]
Hi! Sorry for the very long answer delay. I see the limitation. Because of OWL serialization is quite specific and well structured, what about directly serializing the OWL structure to Turtle without having to deal with RDF basic model explicitly? It might allow a much simpler code with better performances.

**Comment by phillord** [comment]
Turtle is not an answer for me I am afraid. Most of the ontologies that I work with use RDF/XML as their main form of serialisation. If I was going to switch formats, I would use the XML representation of OWL and not use RDF at all. The code base for this is, indeed, simpler and with better performance.

**Comment by Tpt** [comment]
Sorry, I said Turtle for RDF/XML. I should have proofread myself. Indeed, OWL XML is much simpler than RDF/XML for OWL.

**Comment by phillord** [comment]
Yes, that might also be a reasonable route forward. I figured that the RDF rendering would be a pain, and so it might make more sense to use a library. But having tried with both sophia and rio, it's not so clear that this is helping.  I guess the main advantage of using an RDF data model is that the specification is written in terms of triples, so my writer and reader look rather like the spec, but I could parse it out directly to XML.

However, I'm not likely to rewrite it at this point, at least not in the short term, and I'd rather work on doing something with the OWL that I have parsed! 

I think we are coming to decision point. I guess that you don't want to integrate this into Rio, quite reasonably as it's not trivial. It's reasonable straight forward for me to make this standalone. I can probably even make the data model simpler -- the distinction between NamedOrBlank, Named, or Term isn't really buying me much in the OWL code except quite a lot of "into" statements. Shall I assume that this is the way forward?

**Comment by Tpt** [comment]
Yes, it seems the best way forward imho. Thank you for all your work on this!

**Comment by phillord** [comment]
No worries!

**Comment by phillord** [comment]
Now available as https://github.com/phillord/pretty_rdf.

**Pull request closed without merging**
